# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import robot_pb2 as robot__pb2


class RobotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerLlantas = channel.unary_unary(
                '/RobotService/ObtenerLlantas',
                request_serializer=robot__pb2.Request.SerializeToString,
                response_deserializer=robot__pb2.Llanta.FromString,
                )


class RobotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ObtenerLlantas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerLlantas': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerLlantas,
                    request_deserializer=robot__pb2.Request.FromString,
                    response_serializer=robot__pb2.Llanta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RobotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RobotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObtenerLlantas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RobotService/ObtenerLlantas',
            robot__pb2.Request.SerializeToString,
            robot__pb2.Llanta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
