# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\" \n\x06Llanta\x12\n\n\x02wl\x18\x01 \x01(\x02\x12\n\n\x02wr\x18\x02 \x01(\x02\"\x18\n\x07Request\x12\r\n\x05query\x18\x01 \x01(\t23\n\x0cRobotService\x12#\n\x0eObtenerLlantas\x12\x08.Request\x1a\x07.Llantab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LLANTA']._serialized_start=15
  _globals['_LLANTA']._serialized_end=47
  _globals['_REQUEST']._serialized_start=49
  _globals['_REQUEST']._serialized_end=73
  _globals['_ROBOTSERVICE']._serialized_start=75
  _globals['_ROBOTSERVICE']._serialized_end=126
# @@protoc_insertion_point(module_scope)
